version: '3'
services:
  flaskapi1:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: flaskapp
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: myregistry.azurecr.io/flaskapp
    container_name: flaskapp
    environment:
      REDIS: flaskapp
    ports:
        - "80:80"
